### ISSUE TITLE
Edge Predictor gets Downloaded Every Time A Unity App Runs

### ISSUE THREAD

**Issue by jkorn2324** [fxnai/fxn3d#2]
Whenever our app first calls the Create Predictor function for an Edge Predictor, Function still downloads the Predictor even if we already have it cached on our device from a previous play session.

How to Reproduce:
- Run the Unity Project
- Call Create function on an edge Predictor
- Stop Running the Unity Project
- Run the Unity Project again
- Call Create function on an edge Predictor

Devices Affected (Untested on Other Devices):
- MacOS M1 Silicon

**Comment by olokobayusuf** [comment]
Fixed in [0.0.22](https://github.com/fxnai/fxn3d/releases/tag/0.0.22).
