### ISSUE TITLE
WebException: The request was aborted: The request was canceled.

### ISSUE THREAD

**Issue by SimonDarksideJ** [fxnai/fxn3d#6]
Hitting an issue where we are currently unable to perform "Build & Run" builds to deploy to the device and it seems I've been blaming Unity incorrectly.

The issue actually comes from the 

> ai.fxn.hn3d package -> ai.fxn.fxn3d/editor/build/AndroidBuildHandler.cs
>
> IPostGenerateGradleAndroidProject.OnPostGenerateGradleAndroidProject

Is there a workaround for this as we are only using VideoKit and NONE of the AI features

We can do a manual build, but as we are building an Android aab delivery, this reduces our capability to test locally.

**Comment by olokobayusuf** [comment]
@SimonDarksideJ what version of VideoKit are you on?

**Comment by SimonDarksideJ** [comment]
We were on 0.19 and missed the announcement of the shift to a new npm domain and the rename.  Just updating to 21 and the new NPM package and re-testing now

**Comment by SimonDarksideJ** [comment]
Closed as this issue is redundant after an upgrade to 0.21 and a different "known" issue was hit

**Comment by olokobayusuf** [comment]
Moving to #5
