### ISSUE TITLE
Compiler errors because of `arm64` library on Windows

### ISSUE THREAD

**Issue by gaopanleo** [fxnai/fxn3d#7]
Library/PackageCache/ai.fxn.fxn3d@0.0.29/Plugins/Windows/arm64/Function.dll', expected x64 architecture, but was ARM64 architecture. You must recompile your plugin for x64 architecture.

win10 ; unity2021.3.27f1

**Comment by olokobayusuf** [comment]
Hey @gaopanleo it turns out Function has required Unity 2022.3+ for quite some time; we failed to update the README to mention this fact. Unity 2021 doesn't support `arm64` architecture on Windows.
