### ISSUE TITLE
Internet Connection Required for Function Even If Cached

### ISSUE THREAD

**Issue by jkorn2324** [fxnai/fxn3d#8]
Issue: In order to use Function as of Function 0.0.29, users have to be connected to wifi in order to download the Predictor even if the Predictor is already cached on their file system.

Expected Output: The predictor should still be loaded and be usable if the following is met:
- The predictor has been loaded in remotely using an internet connection before and cached to device
- The user is currently without an internet connection

Technical Specs:
- Unity Version 2022.3.20f1
- Fxn 0.0.29
- Platform - Any (Tested on Windows Standalone, Windows Editor, & iOS)

How to Reproduce (In the Unity Editor): 
- Step 1: Create a script that loads in a predictor (or use a sample Predictor scene)
- Step 2: Disconnect from Internet
- Step 3: Run project

Here is the error that gets logged in the Console:
![IMG_5394](https://github.com/user-attachments/assets/704f4fc0-4b84-4b71-a4b6-9743b36691dd)

**Comment by olokobayusuf** [comment]
This has been fixed and will be released in 0.0.30.

**Comment by olokobayusuf** [comment]
[0.0.30](https://github.com/fxnai/fxn3d/releases/tag/0.0.30) is live!
